In [1]:
import pandas as pd
df = pd.read_csv('./scrapper/survData_03032020.csv')

In [2]:
df['Property_name']=df['Property_name'].str.strip()
spt = df.groupby(df['Property_name'].str.lower())
spt.first()

,Property_name,Renting_price,Category,Size,Bedroom,Bathroom,Property_Details,lat,lng,WiFi,...,SwmPool,Kitchen,Wardrobe,Fridge,Sofa,TV,Heater,ShuttleVan,Satisfaction_level,population
Property_name,,,,,,,,,,,,,,,,,,,,,
beijing,Beijing,315,Room,0,1,1,"WiFi, Car Park, House Keeping Services, Laundr...",4.330476,101.136440,1,...,0,0,1,1,0,0,0,0,3,4
cambridge,Cambridge,240,Room,0,1,1,"WiFi, Car Park, House Keeping Services, Laundr...",4.331954,101.131343,1,...,0,1,1,1,0,0,1,0,4,8
champs,Champs,560,Room,0,1,1,"Car Park, Air Conditioner, House Keeping Servi...",4.322275,101.125011,0,...,1,1,1,1,0,0,1,0,4,2
eastlake,Eastlake,450,House,0,3,2,"Car Park, Kitchen, Wardrobe, Fridge",4.338707,101.152246,0,...,0,1,1,1,0,0,0,0,3,1
harvard,Harvard,240,Room,0,1,1,"Car Park, Washing Machine, Kitchen, Wardrobe, ...",4.329960,101.131426,0,...,0,1,1,1,0,0,1,0,3,1
imperial,Imperial,3450,House,0,11,11,"WiFi, House Keeping Services, Washing Machine,...",4.333124,101.131828,1,...,0,0,1,1,0,0,1,0,4,10
kampar putra,Kampar Putra,900,Room,0,1,1,"WiFi, Car Park, Air Conditioner, Washing Machi...",4.320514,101.131030,1,...,0,1,0,1,1,1,1,0,4,4
mahsuri,Mahsuri,310,Room,0,1,1,"WiFi, Car Park, Air Conditioner, Washing Machi...",4.328722,101.151172,1,...,0,1,1,1,1,0,1,0,3,7
manchester,Manchester,270,Room,0,1,1,"WiFi, Air Conditioner, House Keeping Services,...",4.328437,101.135307,1,...,0,0,1,1,0,0,1,0,5,10
meadow park,Meadow Park,1150,Apartment,0,4,3,"WiFi, Car Park, Air Conditioner, Washing Machi...",4.315885,101.123556,1,...,1,1,1,1,1,1,1,1,3,4
oxford,Oxford,170,Room,0,1,1,"WiFi, House Keeping Services, Washing Machine,...",4.329492,101.136502,1,...,0,0,0,1,0,0,1,0,4,10
pangsapuri sutera,Pangsapuri Sutera,220,Apartment,0,3,2,"WiFi, Car Park, Air Conditioner, House Keeping...",4.330136,101.145036,1,...,0,0,0,1,0,0,0,0,1,4
standford,Standford,250,House,0,1,1,"Washing Machine, Kitchen, Fridge, Water Heater",4.327140,101.135105,0,...,0,1,0,1,0,0,1,0,3,4
trails,trails,350,Room,0,1,1,"Car Park, Air Conditioner, Washing Machine, Dr...",4.319671,101.123311,0,...,1,1,1,1,1,0,1,0,4,3
tsing hua,Tsing Hua,280,Room,0,1,1,"WiFi, House Keeping Services, Washing Machine,...",4.329354,101.136492,1,...,0,1,0,1,0,0,1,0,2,9
westcity,Westcity,700,House,0,3,2,"Car Park, Air Conditioner, Washing Machine, Sw...",4.322051,101.127148,0,...,1,1,0,1,1,0,1,1,4,4
westcity condo,Westcity Condo,450,Room,0,1,1,"WiFi, Car Park, Air Conditioner, Washing Machi...",4.323742,101.129656,1,...,1,1,1,1,1,0,1,1,4,4
westlake villas,Westlake Villas,650,Room,0,1,1,"WiFi, Car Park, Air Conditioner, House Keeping...",4.327772,101.133221,1,...,1,1,1,1,1,0,1,1,4,2
yale,Yale,300,Room,0,1,1,"Car Park, House Keeping Services, Washing Mach...",4.328169,101.135322,0,...,0,0,0,1,1,0,1,0,4,5

In [3]:
house

,Property_name,Renting_price,Category,Size,Bedroom,Bathroom,Property_Details,lat,lng,WiFi,...,SwmPool,Kitchen,Wardrobe,Fridge,Sofa,TV,Heater,ShuttleVan,Satisfaction_level,population
11,Imperial,3450,House,0.0,11,11,"WiFi, House Keeping Services, Washing Machine,...",0.0,0.0,1,...,0,0,1,1,0,0,1,0,4,10
15,West city,700,House,0.0,3,2,"Car Park, Air Conditioner, Washing Machine, Sw...",0.0,0.0,0,...,1,1,0,1,1,0,1,1,4,4
18,Trails of kampar,1000,House,0.0,3,2,"Car Park, Air Conditioner, Washing Machine, Dr...",0.0,0.0,0,...,1,1,1,1,1,1,1,0,5,4
27,Cambridge,3350,House,0.0,14,12,"WiFi, Car Park, House Keeping Services, Laundr...",0.0,0.0,1,...,0,1,1,1,0,0,1,0,4,8
29,Harvard,900,House,0.0,4,4,"Car Park, Washing Machine, Kitchen, Wardrobe, ...",0.0,0.0,0,...,0,1,1,1,1,0,1,0,4,6
31,Westcity,225,House,0.0,3,2,"WiFi, Car Park, Air Conditioner, Washing Machi...",0.0,0.0,1,...,1,1,1,1,1,1,1,1,4,5
32,Harvard,900,House,0.0,4,4,"Washing Machine, Wardrobe, Fridge, Sofa",0.0,0.0,0,...,0,0,1,1,1,0,0,0,4,6
36,Beijing,3350,House,0.0,12,12,"WiFi, Car Park, House Keeping Services, Washin...",0.0,0.0,1,...,0,1,1,1,0,0,1,0,3,14
44,trails,1200,House,0.0,3,2,"Car Park, Air Conditioner, Washing Machine, Gy...",0.0,0.0,0,...,1,1,1,1,1,1,1,0,4,4
47,Harvard,900,House,0.0,4,4,"Car Park, Washing Machine, Fridge, Sofa",0.0,0.0,0,...,0,0,0,1,1,0,0,0,3,5
53,Harvard,280,House,0.0,1,1,"Car Park, House Keeping Services, Washing Mach...",0.0,0.0,0,...,0,1,1,1,0,0,1,0,4,4
54,Harvard,1150,House,0.0,4,3,"Car Park, House Keeping Services, Washing Mach...",0.0,0.0,0,...,0,1,1,1,0,0,1,0,4,4
55,Harvard,140,House,0.0,1,1,"WiFi, Car Park, House Keeping Services, Laundr...",0.0,0.0,1,...,0,1,0,1,0,0,1,0,4,4
56,Harvard,560,House,0.0,4,4,"WiFi, Car Park, House Keeping Services, Laundr...",0.0,0.0,1,...,0,1,0,1,0,0,1,0,4,4
58,Stanford,250,House,0.0,1,1,"Washing Machine, Kitchen, Fridge, Water Heater",0.0,0.0,0,...,0,1,0,1,0,0,1,0,3,4
59,Stanford,900,House,0.0,4,4,"Washing Machine, Kitchen, Fridge, Water Heater",0.0,0.0,0,...,0,1,0,1,0,0,1,0,3,4
74,Imperial,3750,House,0.0,12,12,"WiFi, Air Conditioner, Washing Machine, Kitche...",0.0,0.0,1,...,0,1,1,1,1,1,1,0,5,12
84,Trails of Kampar,800,House,0.0,3,2,"Car Park, Air Conditioner, Washing Machine, Dr...",0.0,0.0,0,...,1,1,1,1,1,1,0,1,5,5
85,Cambridge,295,House,0.0,14,13,"WiFi, House Keeping Services, Washing Machine,...",0.0,0.0,1,...,0,1,1,1,0,1,1,0,5,14
87,Eastlake,450,House,0.0,3,2,"Car Park, Kitchen, Wardrobe, Fridge",0.0,0.0,0,...,0,1,1,1,0,0,0,0,3,1